-- ============================================================================
-- ATLAS — Core schema
-- Run in Supabase SQL editor, or via `supabase db push` if you use the CLI.
-- ============================================================================

create extension if not exists "uuid-ossp";

-- ----------------------------------------------------------------------------
-- PROFILES (extends Supabase auth.users)
-- ----------------------------------------------------------------------------
create type user_role as enum ('customer', 'admin', 'manager', 'owner');

create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role user_role not null default 'customer',
  loyalty_points int not null default 0,
  referral_code text unique,
  referred_by text references profiles(referral_code),
  notify_new_categories boolean not null default true,
  notify_tag_matches boolean not null default true,
  notify_order_updates boolean not null default true,
  notify_rewards boolean not null default false,
  created_at timestamptz not null default now()
);

-- Auto-create a profile row whenever someone signs up
create function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, referral_code)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    upper(substr(md5(random()::text), 1, 8))
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

-- ----------------------------------------------------------------------------
-- LEAGUES & CATEGORIES
-- ----------------------------------------------------------------------------
create table leagues (
  slug text primary key,
  name text not null,
  country text not null,
  primary_color text not null,
  secondary_color text not null,
  logo_url text,
  logo_has_wordmark boolean not null default false, -- true if the logo image already spells out the league name
  sort_order int not null default 0
);

create type product_category as enum ('shirts', 'socks', 'balls', 'shinpads', 'sportswear');
create type product_gender as enum ('male', 'female', 'unisex');

create table tags (
  id uuid primary key default uuid_generate_v4(),
  label text not null unique
);

-- ----------------------------------------------------------------------------
-- PRODUCTS
-- ----------------------------------------------------------------------------
create table products (
  id uuid primary key default uuid_generate_v4(),
  code text unique, -- internal code, generated by trigger below; owner/manager/admin only
  name text not null,
  category product_category not null,
  league_slug text references leagues(slug),
  team text,
  description text,
  price_usd numeric(10,2) not null,
  compare_at_usd numeric(10,2),
  cost_usd numeric(10,2), -- for margin calculations, owner/manager only via RLS
  gender product_gender not null default 'unisex',
  sizes text[] not null default '{}',
  out_of_stock_sizes text[] not null default '{}',
  stock int not null default 0,
  low_stock_threshold int not null default 6,
  coming_soon boolean not null default false,
  hot boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'published')),
  image_url text,
  rating numeric(2,1) not null default 0,
  review_count int not null default 0,
  created_at timestamptz not null default now()
);

create table product_tags (
  product_id uuid references products(id) on delete cascade,
  tag_id uuid references tags(id) on delete cascade,
  primary key (product_id, tag_id)
);

-- Per-category (per-league) visual styling — Owner/Manager editable only
create table category_styles (
  league_slug text primary key references leagues(slug) on delete cascade,
  font_family text,
  updated_by uuid references profiles(id),
  updated_at timestamptz not null default now()
);

-- Product code generator: ATL-<CAT3>-<sequence>
create sequence product_code_seq;

create function generate_product_code()
returns trigger as $$
declare
  cat_prefix text;
begin
  cat_prefix := upper(substr(new.category::text, 1, 3));
  new.code := 'ATL-' || cat_prefix || '-' || lpad(nextval('product_code_seq')::text, 4, '0');
  return new;
end;
$$ language plpgsql;

create trigger set_product_code
  before insert on products
  for each row
  when (new.code is null)
  execute procedure generate_product_code();

-- ----------------------------------------------------------------------------
-- REVIEWS
-- ----------------------------------------------------------------------------
create table reviews (
  id uuid primary key default uuid_generate_v4(),
  product_id uuid not null references products(id) on delete cascade,
  user_id uuid references profiles(id) on delete set null,
  author_name text not null,
  rating int not null check (rating between 1 and 5),
  body text not null,
  photo_url text,
  created_at timestamptz not null default now()
);

-- Keep products.rating / review_count in sync
create function refresh_product_rating()
returns trigger as $$
begin
  update products p
  set rating = coalesce((select avg(rating) from reviews where product_id = p.id), 0),
      review_count = (select count(*) from reviews where product_id = p.id)
  where p.id = coalesce(new.product_id, old.product_id);
  return null;
end;
$$ language plpgsql;

create trigger reviews_rating_sync
  after insert or update or delete on reviews
  for each row execute procedure refresh_product_rating();

-- ----------------------------------------------------------------------------
-- WISHLIST
-- ----------------------------------------------------------------------------
create table wishlist_items (
  user_id uuid references profiles(id) on delete cascade,
  product_id uuid references products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ----------------------------------------------------------------------------
-- ORDERS
-- ----------------------------------------------------------------------------
create type order_status as enum ('placed', 'confirmed', 'shipped', 'delivered', 'cancelled');
create type order_channel as enum ('website', 'instagram', 'whatsapp');
create type payment_method as enum ('whish_pay', 'omt', 'card', 'cod');

create sequence order_number_seq start 10001;

create table orders (
  id uuid primary key default uuid_generate_v4(),
  order_number text unique,
  user_id uuid references profiles(id) on delete set null,
  status order_status not null default 'placed',
  channel order_channel not null default 'website',
  payment_method payment_method not null,
  customer_name text not null,
  customer_phone text,
  customer_email text,
  address text not null,
  city text,
  subtotal_usd numeric(10,2) not null,
  is_preorder boolean not null default false,
  logged_by uuid references profiles(id), -- set when admin manually logs an IG/WhatsApp order
  telegram_notified boolean not null default false,
  receipt_sent boolean not null default false,
  created_at timestamptz not null default now()
);

create function generate_order_number()
returns trigger as $$
begin
  new.order_number := 'ATL-' || nextval('order_number_seq')::text;
  return new;
end;
$$ language plpgsql;

create trigger set_order_number
  before insert on orders
  for each row
  when (new.order_number is null)
  execute procedure generate_order_number();

create table order_items (
  id uuid primary key default uuid_generate_v4(),
  order_id uuid not null references orders(id) on delete cascade,
  product_id uuid references products(id),
  product_name text not null, -- snapshot in case product changes later
  size text,
  qty int not null default 1,
  unit_price_usd numeric(10,2) not null
);

create table return_requests (
  id uuid primary key default uuid_generate_v4(),
  order_id uuid not null references orders(id) on delete cascade,
  user_id uuid references profiles(id),
  type text not null check (type in ('return', 'exchange')),
  reason text not null,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected', 'completed')),
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- REFERRALS
-- ----------------------------------------------------------------------------
create table referral_redemptions (
  id uuid primary key default uuid_generate_v4(),
  code text not null references profiles(referral_code),
  redeemed_by uuid references profiles(id),
  order_id uuid references orders(id),
  reward_usd numeric(10,2) not null default 10,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- SEARCH ANALYTICS
-- ----------------------------------------------------------------------------
create table search_logs (
  id uuid primary key default uuid_generate_v4(),
  term text not null,
  result_count int not null,
  user_id uuid references profiles(id),
  created_at timestamptz not null default now()
);

-- Helpful index for the zero-result-search admin view
create index idx_search_logs_zero_results on search_logs (term) where result_count = 0;
create index idx_products_league on products(league_slug);
create index idx_products_category on products(category);
create index idx_orders_status on orders(status);
